export const MAX_VIDEO_SIZE_MB = 20;
export const SUPPORTED_MIME_TYPES = ['video/mp4', 'video/quicktime', 'video/webm'];
export const SUPPORTED_IMAGE_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/heic'];

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'zh-TW', label: '繁體中文' },
  { code: 'zh-CN', label: '简体中文' },
  { code: 'ja', label: '日本語' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
];

export type LanguageCode = 'en' | 'zh-TW' | 'zh-CN' | 'ja' | 'es' | 'fr';

export const DIETARY_OPTIONS = [
  { value: "Vegetarian", label: { en: "Vegetarian", "zh-TW": "蛋奶素", "zh-CN": "蛋奶素", ja: "ベジタリアン", es: "Vegetariano", fr: "Végétarien" } },
  { value: "Vegan", label: { en: "Vegan", "zh-TW": "全素", "zh-CN": "全素", ja: "ヴィーガン", es: "Vegano", fr: "Végétalien" } },
  { value: "Gluten-Free", label: { en: "Gluten-Free", "zh-TW": "無麩質", "zh-CN": "无麸质", ja: "グルテンフリー", es: "Sin Gluten", fr: "Sans gluten" } },
  { value: "No Beef", label: { en: "No Beef", "zh-TW": "不吃牛", "zh-CN": "不吃牛", ja: "牛肉なし", es: "Sin Res", fr: "Sans bœuf" } },
  { value: "No Pork", label: { en: "No Pork", "zh-TW": "不吃豬", "zh-CN": "不吃猪", ja: "豚肉なし", es: "Sin Cerdo", fr: "Sans porc" } },
  { value: "Nut-Free", label: { en: "Nut-Free", "zh-TW": "無堅果", "zh-CN": "无堅果", ja: "ナッツフリー", es: "Sin Nueces", fr: "Sans noix" } },
  { value: "Dairy-Free", label: { en: "Dairy-Free", "zh-TW": "無乳製品", "zh-CN": "无乳制品", ja: "乳製品なし", es: "Sin Lácteos", fr: "Sans produits laitiers" } }
];

export const VOICE_OPTIONS = [
  { id: 'Puck', label: 'Classic Chef (Male)', gender: 'Male' },
  { id: 'Kore', label: 'Classic Chef (Female)', gender: 'Female' },
];

export const ALARM_OPTIONS = [
  { id: 'soft-chime', label: 'Soft Chime' },
  { id: 'warm-gong', label: 'Warm Gong' },
  { id: 'classic', label: 'Classic Beep' },
];

export const AVATARS = [
  { 
    id: 'chef_vibe', 
    name: { en: 'Chef Vibe', "zh-TW": "Vibe 主廚", "zh-CN": "Vibe 主厨", ja: "シェフ・バイブ", es: "Chef Vibe", fr: "Chef Vibe" }, 
    emoji: '👨‍🍳', 
    color: 'bg-orange-100', 
    voiceName: 'Puck',
    systemInstruction: "You are a friendly, helpful AI Chef Assistant."
  },
  { 
    id: 'grandma', 
    name: { en: 'Grandma', "zh-TW": "慈祥奶奶", "zh-CN": "慈祥奶奶", ja: "おばあちゃん", es: "Abuela", fr: "Grand-mère" }, 
    emoji: '👵', 
    color: 'bg-green-100', 
    voiceName: 'Kore',
    systemInstruction: "You are a sweet, encouraging grandmother who loves traditional cooking methods."
  }, 
  { 
    id: 'gordon', 
    name: { en: 'Gordon', "zh-TW": "嚴格主廚", "zh-CN": "严格主厨", ja: "ゴードン", es: "Gordon", fr: "Gordon" }, 
    emoji: '😤', 
    color: 'bg-red-100', 
    voiceName: 'Fenrir',
    systemInstruction: "You are a strict, demanding, but brilliant chef who accepts nothing but perfection."
  },
];

export const PANTRY_STAPLES_KEYWORDS = [
  'salt', 'pepper', 'oil', 'sugar', 'water', 'soy sauce', 'vinegar', 'flour', 'butter', 'honey', 'ketchup', 'mustard', 'mayo',
  '鹽', '塩', '胡椒', '油', '糖', '醬油', '酱油', '醋', '水', '麵粉', '面粉', '奶油', '蜂蜜', '番茄醬', '番茄酱'
];

export const UI_TEXT = {
  en: {
    title: "Vibe Cooking",
    subtitle: "", // Not used directly, replaced by dynamic greeting
    subtitleHighlight: "What are we making?",
    greetingMorning: "Good Morning,",
    greetingAfternoon: "Good Afternoon,",
    greetingEvening: "Good Evening,",
    description: "Show us your leftovers or list your ingredients. We'll turn them into a gourmet meal.",
    videoScan: "Scan Ingredients",
    photoScan: "Photo Scan",
    textInput: "Text Input",
    recordFridge: "Scan your Fridge or Pantry",
    takePhoto: "Snap your Ingredients",
    recordHint: "Take a photo or short video. Speak: \"I have these leftovers...\"",
    photoHint: "Take a clear photo of your open fridge or pantry items.",
    openCamera: "Open Camera / Upload",
    dietaryRestrictions: "DIETARY RESTRICTIONS",
    findRecipes: "Find Recipes",
    analyzing: "Analyzing...",
    ingredientsTitle: "What's in your pantry?",
    ingredientsHint: "List your ingredients and we'll handle the rest.",
    ingredientsLabel: "Ingredients / Dishes",
    ingredientsPlaceholder: "e.g. 'Chicken, Onions' OR 'Borscht, Pasta'",
    cravingLabel: "Craving (Optional)",
    cravingPlaceholder: "e.g. Something spicy, breakfast...",
    otherRestrictionPlaceholder: "Other (e.g. Low Sodium)",
    generating: "Generating Recipes...",
    foundTitle: "Here's what I found",
    yourRequest: "Your Request",
    missing: "Missing",
    cookThis: "Cook This",
    scanDifferent: "Scan a different item",
    step: "STEP",
    of: "OF",
    finishCooking: "Finish Cooking",
    nextStep: "Next Step",
    previous: "Previous",
    chefsTip: "Chef's Tip",
    done: "Done!",
    prepTitle: "Let's Get Ready",
    prepSubtitle: "Gather these ingredients before we start.",
    youHave: "You Have",
    youNeed: "You Need (Missing)",
    startCooking: "Start Cooking",
    exitMode: "Exit Cooking Mode",
    repeat: "Repeat",
    speaking: "Speaking...",
    recipeOverview: "Recipe Overview",
    myCookbook: "My Cookbook",
    savedRecipes: "Saved Recipes",
    noSavedRecipes: "No saved recipes yet.",
    remove: "Remove",
    servings: "Servings",
    ingredientsList: "Ingredients List",
    liveChef: "Live Chef",
    liveChefHint: "Tap to talk to your AI Chef Assistant",
    update: "Update",
    updating: "Updating...",
    // Overview & Planning
    chefsPlan: "Chef's Plan",
    chefsPlanSubtitle: "Based on time & complexity, here is the suggested order.",
    priority: "Priority",
    estTime: "Est. Time",
    startWith: "Start with",
    then: "Then",
    finally: "Finally",
    totalTime: "Total Est. Time",
    overview: "Overview",
    // FoodStylist
    foodStylist: "AI Food Stylist",
    uploadDish: "Upload your dish",
    stylePrompt: "How should we style it?",
    stylePlaceholder: "e.g. Make it look like a Michelin star plating, add cinematic lighting...",
    styling: "Styling...",
    generateStyle: "Generate Style",
    download: "Download",
    share: "Share",
    chooseAvatar: "Choose your Chef",
    // Music
    cozyVibes: "Cozy Vibes",
    // Settings
    settings: "Settings",
    voiceLabel: "Chef's Voice",
    alarmLabel: "Timer Sound",
    preview: "Preview",
    close: "Close",
    regenerateRecipes: "Regenerate Recipes",
    timer: "Timer"
  },
  "zh-TW": {
    title: "靈感廚房",
    subtitle: "",
    subtitleHighlight: "今天要做什麼？",
    greetingMorning: "早安，",
    greetingAfternoon: "午安，",
    greetingEvening: "晚安，",
    description: "拍下冰箱裡的剩菜，或輸入現有食材。我們將為您變出一道美味佳餚。",
    videoScan: "掃描食材",
    photoScan: "照片掃描",
    textInput: "文字輸入",
    recordFridge: "拍攝您的冰箱或食材",
    takePhoto: "拍攝您的食材",
    recordHint: "拍攝照片或約10秒的影片。邊拍邊說：「我有這些剩菜...」",
    photoHint: "拍一張清晰的冰箱或食材照片。",
    openCamera: "開啟相機 / 上傳",
    dietaryRestrictions: "飲食限制",
    findRecipes: "尋找食譜",
    analyzing: "分析中...",
    ingredientsTitle: "冰箱裡有什麼？",
    ingredientsHint: "列出您的食材，剩下的交給我們。",
    ingredientsLabel: "食材 / 料理名稱",
    ingredientsPlaceholder: "例如：'雞肉, 洋蔥' 或 '羅宋湯, 義大利麵'",
    cravingLabel: "想吃什麼 (選填)",
    cravingPlaceholder: "例如：想吃辣的、早餐...",
    otherRestrictionPlaceholder: "其他需求 (例如：低鈉、清淡)",
    generating: "食譜生成中...",
    foundTitle: "分析結果",
    yourRequest: "您的需求",
    missing: "缺少",
    cookThis: "開始烹飪",
    scanDifferent: "重新掃描/輸入",
    step: "步驟",
    of: "/",
    finishCooking: "完成烹飪",
    nextStep: "下一步",
    previous: "上一步",
    chefsTip: "主廚秘訣",
    done: "完成！",
    prepTitle: "準備開始",
    prepSubtitle: "在開始之前，請先準備好以下食材。",
    youHave: "您有的食材",
    youNeed: "您缺少的食材",
    startCooking: "開始料理",
    exitMode: "退出烹飪模式",
    repeat: "重聽指令",
    speaking: "朗讀中...",
    recipeOverview: "食譜總覽",
    myCookbook: "我的食譜",
    savedRecipes: "收藏食譜",
    noSavedRecipes: "尚未收藏任何食譜。",
    remove: "移除",
    servings: "份量",
    ingredientsList: "需準備的食材",
    liveChef: "真人語音助手",
    liveChefHint: "點擊與 AI 主廚對話",
    update: "更新",
    updating: "更新中...",
    // Overview & Planning
    chefsPlan: "主廚計畫",
    chefsPlanSubtitle: "根據時間與複雜度，這是我們建議的烹飪順序。",
    priority: "優先順序",
    estTime: "預估時間",
    startWith: "先做",
    then: "接著做",
    finally: "最後做",
    totalTime: "總預估時間",
    overview: "總覽",
    // FoodStylist
    foodStylist: "AI 美食擺盤師",
    uploadDish: "上傳您的料理",
    stylePrompt: "您想如何呈現？",
    stylePlaceholder: "例如：米其林星級擺盤、電影感光影...",
    styling: "生成中...",
    generateStyle: "生成風格",
    download: "下載",
    share: "分享",
    chooseAvatar: "選擇您的主廚",
    // Music
    cozyVibes: "舒適氛圍",
    // Settings
    settings: "設定",
    voiceLabel: "主廚聲音",
    alarmLabel: "計時器鈴聲",
    preview: "試聽",
    close: "關閉",
    regenerateRecipes: "重新生成食譜",
    timer: "計時器"
  },
  "zh-CN": {
    title: "灵感厨房",
    subtitle: "",
    subtitleHighlight: "今天要做什么？",
    greetingMorning: "早安，",
    greetingAfternoon: "午安，",
    greetingEvening: "晚安，",
    description: "拍下冰箱里的剩菜，或输入现有食材。我们将为您变出一道美味佳肴。",
    videoScan: "扫描食材",
    photoScan: "照片扫描",
    textInput: "文字输入",
    recordFridge: "拍摄您的冰箱或食材",
    takePhoto: "拍摄您的食材",
    recordHint: "拍摄照片或约10秒的视频。边拍边说：“我有这些剩菜...”",
    photoHint: "拍一张清晰的冰箱或食材照片。",
    openCamera: "开启相机 / 上传",
    dietaryRestrictions: "饮食限制",
    findRecipes: "寻找食谱",
    analyzing: "分析中...",
    ingredientsTitle: "冰箱里有什么？",
    ingredientsHint: "列出您的食材，剩下的交给我们。",
    ingredientsLabel: "食材 / 料理名称",
    ingredientsPlaceholder: "例如：'鸡肉, 洋葱' 或 '罗宋汤, 意大利面'",
    cravingLabel: "想吃什么 (选填)",
    cravingPlaceholder: "例如：想吃辣的、早餐...",
    otherRestrictionPlaceholder: "其他需求 (例如：低钠、清淡)",
    generating: "食谱生成中...",
    foundTitle: "分析结果",
    yourRequest: "您的需求",
    missing: "缺少",
    cookThis: "开始烹饪",
    scanDifferent: "重新扫描/输入",
    step: "步骤",
    of: "/",
    finishCooking: "完成烹饪",
    nextStep: "下一步",
    previous: "上一步",
    chefsTip: "主厨秘诀",
    done: "完成！",
    prepTitle: "准备开始",
    prepSubtitle: "在开始之前，请先准备好以下食材。",
    youHave: "您有的食材",
    youNeed: "您缺少的食材",
    startCooking: "开始料理",
    exitMode: "退出烹饪模式",
    repeat: "重听指令",
    speaking: "朗读中...",
    recipeOverview: "食谱总览",
    myCookbook: "我的食谱",
    savedRecipes: "收藏食谱",
    noSavedRecipes: "尚未收藏任何食谱。",
    remove: "移除",
    servings: "份量",
    ingredientsList: "需准备的食材",
    liveChef: "真人语音助手",
    liveChefHint: "点击与 AI 主厨对话",
    update: "更新",
    updating: "更新中...",
    // Overview & Planning
    chefsPlan: "主厨计划",
    chefsPlanSubtitle: "根据时间与复杂度，这是我们建议的烹饪顺序。",
    priority: "优先顺序",
    estTime: "预估时间",
    startWith: "先做",
    then: "接着做",
    finally: "最后做",
    totalTime: "总预估时间",
    overview: "总览",
    // FoodStylist
    foodStylist: "AI 美食摆盘师",
    uploadDish: "上传您的料理",
    stylePrompt: "您想如何呈现？",
    stylePlaceholder: "例如：米其林星级摆盘、电影感光影...",
    styling: "生成中...",
    generateStyle: "生成风格",
    download: "下载",
    share: "分享",
    chooseAvatar: "选择您的主厨",
    // Music
    cozyVibes: "舒适氛围",
    // Settings
    settings: "设定",
    voiceLabel: "主厨声音",
    alarmLabel: "计时器铃声",
    preview: "试听",
    close: "关闭",
    regenerateRecipes: "重新生成食谱",
    timer: "计时器"
  },
  ja: {
    title: "Vibe Cooking",
    subtitle: "",
    subtitleHighlight: "何を作りましょうか？",
    greetingMorning: "おはようございます、",
    greetingAfternoon: "こんにちは、",
    greetingEvening: "こんばんは、",
    description: "冷蔵庫の余り物を撮影するか、材料を入力してください。美味しい料理に変身させます。",
    videoScan: "食材スキャン",
    photoScan: "写真スキャン",
    textInput: "テキスト入力",
    recordFridge: "冷蔵庫や食材を撮影",
    takePhoto: "食材を撮影",
    recordHint: "写真、または10秒程度の動画。話しかけながら撮影：「これらが残っています...」",
    photoHint: "冷蔵庫や食材の鮮明な写真を撮ってください。",
    openCamera: "カメラを起動 / アップロード",
    dietaryRestrictions: "食事制限",
    findRecipes: "レシピを探す",
    analyzing: "分析中...",
    ingredientsTitle: "パントリーに何がありますか？",
    ingredientsHint: "材料リストを入力すれば、あとはお任せください。",
    ingredientsLabel: "材料 / 料理名",
    ingredientsPlaceholder: "例：'鶏肉, 玉ねぎ' または 'ボルシチ, パスタ'",
    cravingLabel: "今の気分 (任意)",
    cravingPlaceholder: "例：辛いもの、朝食...",
    otherRestrictionPlaceholder: "その他 (例：低塩分)",
    generating: "レシピ生成中...",
    foundTitle: "見つかったもの",
    yourRequest: "リクエスト",
    missing: "不足",
    cookThis: "これを作る",
    scanDifferent: "別の動画をスキャン",
    step: "ステップ",
    of: "/",
    finishCooking: "料理完成",
    nextStep: "次へ",
    previous: "戻る",
    chefsTip: "シェフのヒント",
    done: "完了！",
    prepTitle: "準備しましょう",
    prepSubtitle: "始める前に、以下の材料を揃えてください。",
    youHave: "あるもの",
    youNeed: "必要なもの (不足)",
    startCooking: "料理開始",
    exitMode: "終了する",
    repeat: "もう一度聞く",
    speaking: "読み上げ中...",
    recipeOverview: "レシピ概要",
    myCookbook: "マイレシピ",
    savedRecipes: "保存済みレシピ",
    noSavedRecipes: "保存されたレシピはありません。",
    remove: "削除",
    servings: "分量",
    ingredientsList: "材料リスト",
    liveChef: "AIシェフと話す",
    liveChefHint: "タップしてAIシェフと会話",
    update: "更新",
    updating: "更新中...",
    // Overview & Planning
    chefsPlan: "シェフの計画",
    chefsPlanSubtitle: "時間と複雑さに基づいて、推奨される調理順序です。",
    priority: "優先順位",
    estTime: "目安時間",
    startWith: "最初に",
    then: "次に",
    finally: "最後に",
    totalTime: "総目安時間",
    overview: "概要",
    // FoodStylist
    foodStylist: "AIフードスタイリスト",
    uploadDish: "料理をアップロード",
    stylePrompt: "どのようなスタイルにしますか？",
    stylePlaceholder: "例：ミシュラン星付きのような盛り付け、映画のような照明...",
    styling: "生成中...",
    generateStyle: "スタイル生成",
    download: "ダウンロード",
    share: "共有",
    chooseAvatar: "シェフを選択",
    // Music
    cozyVibes: "Cozy Vibes",
    // Settings
    settings: "設定",
    voiceLabel: "シェフの声",
    alarmLabel: "タイマー音",
    preview: "試聴",
    close: "閉じる",
    regenerateRecipes: "レシピを再生成",
    timer: "タイマー"
  },
  es: {
    title: "Vibe Cooking",
    subtitle: "",
    subtitleHighlight: "¿Qué preparamos hoy?",
    greetingMorning: "Buenos días,",
    greetingAfternoon: "Buenas tardes,",
    greetingEvening: "Buenas noches,",
    description: "Muestra tus sobras or lista tus ingredientes. Los convertiremos en una comida gourmet.",
    videoScan: "Escanear Ingredientes",
    photoScan: "Escanear Foto",
    textInput: "Entrada de Texto",
    recordFridge: "Escanear tu Refrigerador",
    takePhoto: "Fotografía tus ingredientes",
    recordHint: "Toma una foto o video corto. Di: \"Tengo estas sobras...\"",
    photoHint: "Toma una foto clara de tus ingredientes.",
    openCamera: "Abrir Cámara / Subir",
    dietaryRestrictions: "RESTRICCIONES DIETÉTICAS",
    findRecipes: "Buscar Recetas",
    analyzing: "Analizando...",
    ingredientsTitle: "¿Qué hay en tu despensa?",
    ingredientsHint: "Enumera tus ingredientes y nosotros nos encargamos del resto.",
    ingredientsLabel: "Ingredientes / Platos",
    ingredientsPlaceholder: "ej. 'Pollo, Cebolla' O 'Borsch, Pasta'",
    cravingLabel: "Antojo (Opcional)",
    cravingPlaceholder: "ej. Algo picante, desayuno...",
    otherRestrictionPlaceholder: "Otro (ej. Bajo en sodio)",
    generating: "Generando Recetas...",
    foundTitle: "Esto es lo que encontré",
    yourRequest: "Tu Solicitud",
    missing: "Faltante",
    cookThis: "Cocinar Esto",
    scanDifferent: "Escanear otro video",
    step: "PASO",
    of: "DE",
    finishCooking: "Terminar de Cocinar",
    nextStep: "Siguiente Paso",
    previous: "Anterior",
    chefsTip: "Consejo del Chef",
    done: "¡Hecho!",
    prepTitle: "Preparémonos",
    prepSubtitle: "Reúne estos ingredientes antes de empezar.",
    youHave: "Tienes",
    youNeed: "Necesitas (Falta)",
    startCooking: "Empezar a Cocinar",
    exitMode: "Salir del Modo Cocina",
    repeat: "Repetir",
    speaking: "Hablando...",
    recipeOverview: "Resumen de la Receta",
    myCookbook: "Mi Libro de Cocina",
    savedRecipes: "Recetas Guardadas",
    noSavedRecipes: "No hay recetas guardadas.",
    remove: "Eliminar",
    servings: "Porciones",
    ingredientsList: "Lista de Ingredientes",
    liveChef: "Chef en Vivo",
    liveChefHint: "Toca para hablar con tu Chef AI",
    update: "Actualizar",
    updating: "Actualizando...",
    // Overview & Planning
    chefsPlan: "Plan del Chef",
    chefsPlanSubtitle: "Basado en tiempo y complejidad, aquí está el orden sugerido.",
    priority: "Prioridad",
    estTime: "Tiempo Est.",
    startWith: "Empieza con",
    then: "Luego",
    finally: "Finalmente",
    totalTime: "Tiempo Total Est.",
    overview: "Resumen",
    // FoodStylist
    foodStylist: "Estilista de Alimentos AI",
    uploadDish: "Sube tu plato",
    stylePrompt: "¿Cómo quieres estilizarlo?",
    stylePlaceholder: "ej. Emplatado estrella Michelin, iluminación cinematográfica...",
    styling: "Estilizando...",
    generateStyle: "Generar Estilo",
    download: "Descargar",
    share: "Compartir",
    chooseAvatar: "Elige tu Chef",
    // Music
    cozyVibes: "Vibras Acogedoras",
    // Settings
    settings: "Configuración",
    voiceLabel: "Voz del Chef",
    alarmLabel: "Sonido del Temporizador",
    preview: "Vista previa",
    close: "Cerrar",
    regenerateRecipes: "Regenerar Recetas",
    timer: "Temporizador"
  },
  fr: {
    title: "Vibe Cooking",
    subtitle: "",
    subtitleHighlight: "Que préparons-nous ?",
    greetingMorning: "Bonjour,",
    greetingAfternoon: "Bon après-midi,",
    greetingEvening: "Bonsoir,",
    description: "Montrez-nous vos restes ou listez vos ingrédients. Nous en ferons un repas gastronomique.",
    videoScan: "Scanner Ingrédients",
    photoScan: "Scan Photo",
    textInput: "Saisie Texte",
    recordFridge: "Scannez votre Frigo",
    takePhoto: "Photographiez vos ingrédients",
    recordHint: "Prenez une photo ou vidéo. Dites : \"J'ai ces restes...\"",
    photoHint: "Prenez une photo claire de vos ingrédients.",
    openCamera: "Ouvrir Caméra / Mettre en ligne",
    dietaryRestrictions: "RESTRICTIONS ALIMENTAIRES",
    findRecipes: "Trouver des Recettes",
    analyzing: "Analyse en cours...",
    ingredientsTitle: "Qu'y a-t-il dans votre placard ?",
    ingredientsHint: "Listez vos ingrédients et nous nous occupons du reste.",
    ingredientsLabel: "Ingrédients / Plats",
    ingredientsPlaceholder: "ex. 'Poulet, Oignons' OU 'Bortsch, Pâtes'",
    cravingLabel: "Envie (Optionnel)",
    cravingPlaceholder: "ex. Quelque chose d'épicé, petit-déjeuner...",
    otherRestrictionPlaceholder: "Autre (ex. Faible en sodium)",
    generating: "Génération des Recettes...",
    foundTitle: "Voici ce que j'ai trouvé",
    yourRequest: "Votre Demande",
    missing: "Manquant",
    cookThis: "Cuisiner Ça",
    scanDifferent: "Scanner une autre vidéo",
    step: "ÉTAPE",
    of: "SUR",
    finishCooking: "Terminer la Cuisson",
    nextStep: "Étape Suivante",
    previous: "Précédent",
    chefsTip: "Conseil du Chef",
    done: "Terminé !",
    prepTitle: "Préparons-nous",
    prepSubtitle: "Rassemblez ces ingrédients avant de commencer.",
    youHave: "Vous avez",
    youNeed: "Vous avez besoin (Manquant)",
    startCooking: "Commencer à Cuisiner",
    exitMode: "Quitter le Mode Cuisine",
    repeat: "Répéter",
    speaking: "Lecture...",
    recipeOverview: "Aperçu de la Recette",
    myCookbook: "Mon Livre de Cuisine",
    savedRecipes: "Recettes Sauvegardées",
    noSavedRecipes: "Aucune recette sauvegardée.",
    remove: "Supprimer",
    servings: "Portions",
    ingredientsList: "Liste des Ingrédients",
    liveChef: "Chef en Direct",
    liveChefHint: "Appuyez pour parler à votre assistant chef",
    update: "Mettre à jour",
    updating: "Mise à jour...",
    // Overview & Planning
    chefsPlan: "Plan du Chef",
    chefsPlanSubtitle: "Basé sur le temps et la complexité, voici l'ordre suggéré.",
    priority: "Priorité",
    estTime: "Temps Est.",
    startWith: "Commencer par",
    then: "Ensuite",
    finally: "Enfin",
    totalTime: "Temps Total Est.",
    overview: "Aperçu",
    // FoodStylist
    foodStylist: "Styliste Culinaire IA",
    uploadDish: "Téléchargez votre plat",
    stylePrompt: "Comment voulez-vous le styliser ?",
    stylePlaceholder: "ex. Présentation étoilée Michelin, iluminación cinématique...",
    styling: "Création...",
    generateStyle: "Générer le Style",
    download: "Télécharger",
    share: "Partager",
    chooseAvatar: "Choisissez votre Chef",
    // Music
    cozyVibes: "Ambiance Cosy",
    // Settings
    settings: "Paramètres",
    voiceLabel: "Voix du Chef",
    alarmLabel: "Son de l'Alarme",
    preview: "Aperçu",
    close: "Fermer",
    regenerateRecipes: "Régénérer les Recettes",
    timer: "Minuteur"
  }
};


export const getSystemInstruction = (lang: string) => `You are the AI chef for "Vibe Cooking", a sustainable cooking expert.
Your goal is to reduce food waste by creating delicious recipes from limited ingredients.

IMPORTANT: You MUST generate all output content (recipe titles, descriptions, instructions, ingredients, tips) in the following language: "${lang}".

Your Task:
1. Analyze the User Input.
   - **INGREDIENTS MODE**: If the user lists INGREDIENTS (e.g. "chicken, carrots, onions"), generate 3 creative recipes using them to reduce waste.
   - **DISH MODE**: If the user lists SPECIFIC DISH NAMES (e.g. "Borscht, Carbonara", "I want to cook Curry"):
     - Generate recipes for those EXACT dishes. 
     - If the user lists multiple dishes (e.g. "Borscht, Pasta"), generate one recipe for each requested dish.
     - Do NOT invent random recipes if specific dishes are requested.
2. STRICTLY adhere to dietary restrictions.
3. Structure the output as a cooking guide application data source JSON.

Important Rules:
- Prioritize ingredients seen/listed.
- Assume basic pantry staples exist.
- 'durationSeconds' in steps is crucial.
- Output LANGUAGE: ${lang}.
- Ingredients MUST include specific quantities (e.g., '500g chicken', '2 onions', '1 tsp salt').
- Include a 'servings' estimate based on the ingredients (e.g., '2-3 people').
`;